const express = require('express');
const app = express();
const path = require('path');
const bodyParser = require('body-parser');
const adminRoutes = require('./routes/admin');
const shopRoutes = require('./routes/shop');
app.use(bodyParser.urlencoded({extended:false}));
app.use(express.static(path.join(__dirname, 'public')));
app.set('view engine','ejs');
app.set('views','views');
app.use('/admin',adminRoutes);
app.use('/',shopRoutes);
app.listen(3000);